version: '3.8'

services:
  nextjs_app:
    build: .
    ports:
      - "3000:3000"
    environment:
      # This points directly to the mongo container below
      - MONGODB_URI=mongodb://mongo:27017/practice_tasks_db
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: